from Classes import Pessoa

motorista = Pessoa('Luiz', 39)
print(motorista.sexo)
motorista.dirigir('carro')
motorista.falar('celular')
motorista.parardirigir('carro')
motorista.falar('celular')
motorista.pararfalar('celular')
motorista.dirigir('caminhao')
motorista.dirigir('carro')
motorista.falar('WhatsApp')
motorista.parardirigir('caminhão')
print(motorista.estado())
motorista.falar('WhatsApp')
print(motorista.estado())
motorista.pararfalar('Whatsapp')
motorista.dirigir('Carro')
motorista2 = Pessoa('Bruno', 32)
print(motorista2.sexo)
motorista2.falar('WhatsApp')
motorista.dirigir('Carro')
print('===========-==============')
print(motorista.estado())
retorno_verifica_estado = motorista.verifica_estado(False, True)
print(retorno_verifica_estado)
a = motorista.verifica_estado(False, True)
print(a)


